name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ensure this is a supported Python version

    - name: Install distutils
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  
    - name: Run main.py
      run: |
        python main.py
        
    - name: Run test_app.py
      run: |
        pytest test_app.py
        
    - name: Run tests
      run: |
        pytest -v

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
